# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: "https://www.dermabile.es"
lang: es_ES
name: "Dermabile"
author: vanessa
markdown: kramdown

plugins:
  - jekyll-contentblocks
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

permalink: /:categories/:slug

exclude:
  - Gemfile*
  - node_modules
  - vendor
  - bin
  - package*
