# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dra Vanessa Martins
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://www.dermabile.es"

markdown: kramdown

plugins:
  - jekyll-contentblocks

sass:
  style: compressed

permalink: /:categories/:slug

exclude:
  - Gemfile*
  - node_modules
  - vendor
  - bin
  - package*
