# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: "https://www.dermabile.es"
lang: es
name: "Dermábile"
author: vanessa
markdown: kramdown

plugins:
  - jekyll-contentblocks
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /blog/:slug

exclude:
  - Gemfile*
  - node_modules
  - vendor
  - bin
  - package*
  - .tags
  - "*.config.js"
