backend:
  name: git-gateway
  branch: master
media_folder: "assets/images/uploads"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
editor:
  preview: false
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", allow_multiple: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Published", name: "published", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
