backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

editor:
  preview: false

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", allow_multiple: false, required: false }
      - { label: "Date", name: "date", widget: "date", format: "DD-MM-YYYY" }
      - { label: "Published", name: "published", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "services"
    label: "Tratamientos"
    folder: "tratamientos/"
    create: true
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "treatment" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Background image", name: "bg_image", widget: "image", allow_multiple: false, required: true }
      - { label: "Image", name: "image", widget: "image", allow_multiple: false, required: true }
      - { label: "Heading", name: "heading", widget: "markdown" }
      - { label: "Intro", name: "intro", widget: "markdown" }
      - name: benefits
        widget: list
        min: 3
        max: 4
        field:
          - name: item
            widget: object
            fields:
              - name: icon
                widget: image
                allow_multiple: false
              - name: title
                widget: string
              - name: description
                widget: string
