backend:
  name: git-gateway
  branch: master

media_folder: assets/images/uploads

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

editor:
  preview: false

i18n:
  structure: multiple_files
  locales: [es, en, pt]
  default_locale: es

collections:
  - name: blog
    label: Blog
    folder: _posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: layout
        widget: hidden
        default: post
      - name: title
        widget: string
      - name: image
        widget: image
        allow_multiple: false
        required: false
      - name: date
        widget: date
        format: DD-MM-YYYY
      - name: published
        widget: boolean
        default: false
      - name: body
        widget: markdown

  - name: services
    label: Tratamientos
    folder: tratamientos/
    create: true
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    i18n: true
    fields:
      - name: layout
        widget: hidden
        default: treatment
      - name: service_slug
        widget: string
        pattern:
          - "[a-z-]+"
          - "kebab-case: one word replaced spaces with hyphens"
      - name: title
        widget: string
      - name: hero_image
        widget: image
        allow_multiple: false
      - name: intro_image
        widget: image
        allow_multiple: false
      - name: heading
        widget: markdown
      - name: intro
        widget: markdown
      - name: benefits
        widget: list
        field:
          name: item
          widget: object
          fields:
            - name: icon
              widget: image
              allow_multiple: false
            - name: title
              widget: string
            - name: description
              widget: string
      - name: faq
        widget: list
        field:
          name: item
          widget: object
          fields:
            - name: question
              widget: string
            - name: answer
              widget: markdown
